# Generated by Django 3.0.3 on 2020-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.TextField(help_text='Тип документа')),
                ('content', models.TextField(help_text='Содержимое')),
                ('period', models.TextField(help_text='Период')),
                ('authors', models.TextField(help_text='Авторы')),
                ('date_document', models.TextField(help_text='Дата документа')),
                ('archive', models.TextField(help_text='Архив')),
                ('fond', models.TextField(help_text='Фонд')),
                ('opis', models.TextField(help_text='Опись')),
                ('case', models.TextField(help_text='Дело')),
                ('link', models.TextField(help_text='Ссылка на документ')),
            ],
        ),
    ]
